import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Header } from "./ui/header/header.component";
import StoreProvider from "./lib/store/appStoreProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ThemeProvider } from "./themeProvider";

const openSans = Open_Sans({
  weight: "variable",
  subsets: ["latin"],
  axes: ["wdth"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${openSans.className} open-sans-app-font dark:text-white dark:bg-black`}
      >
        <StoreProvider>
          <SessionProvider session={session}>
            <ThemeProvider>
              <header className="sticky z-20 top-0 border-b-[1px] md:border-0">
                <Header />
              </header>
              <div className="max-w-5xl mx-auto pb-5 px-4">{children}</div>
            </ThemeProvider>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
