import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Header } from "./ui/header/header.component";
import StoreProvider from "./lib/store/appStoreProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const openSans = Open_Sans({
  weight: "variable",
  subsets: ["latin"],
  axes: ["wdth"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${openSans.className} open-sans-app-font mx-4`}>
        <StoreProvider>
          <SessionProvider session={session} >
            <header>
              <Header />
            </header>
            <div className="max-w-5xl mx-auto pb-5">{children}</div>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
