import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Header } from "./ui/header/header.component";

const openSans = Open_Sans({
  weight: "variable",
  subsets: ["latin"],
  axes: ["wdth"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  a: React.ReactNode;
  b: React.ReactNode;
  createDialog: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className} open-sans-app-font mx-4`}>
        <header>
          <Header currentUser={null} isAdmin={false} />
        </header>
        <div className="max-w-5xl mx-auto pb-5">{children}</div>
      </body>
    </html>
  );
}
